name: Deploy

on:
  release:
    types:
      - created

jobs:
  dummy-deployment:
    name: Build and echo deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{secrets.MY_SECRET}}
      - run: echo 'Application succesfully deployed!'
